slack:
  url: http://something.com

ctis:
  url: http://something.com
  username: user
  password: pass

recorded_future:
  token: XXXXX

mappings:
  serv_rule: # TODO
    EW:
      - A
      - B
      - C
    PP: ...
    DB: ...
  entities:
    example: # RF source entity type to map
      type: ex_type # Ctis destination entity type (api endpoint)
      param: ex_param # Ctis destination parameter name of the RF main entity field
      description: ex_description # Ctis destination parameter name of the RF entity description
